apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: image-validation
spec:
  ca:
    secretName: ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
  namespace: image-validation
spec:
  isCA: true
  duration: 168h # 7 days
  secretName: ca-secret
  commonName: ca-cert
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: image-validator-tls
  namespace: image-validation
spec:
  duration: 168h # 7 days
  renewBefore: 24h # Renew 1 day before expiry
  secretName: image-validator-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
  dnsNames:
    - image-validator.image-validation.svc
